[tool.poetry]
name = "ai01"
version = "0.1.1a0"
description = ""
authors = ["Om Gupta <omgupta0720@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
huddle01 = {path = "../shinigami/packages/huddle01-python", develop = true}
python-dotenv = "^1.0.1"
pydantic = "^2.10.2"
ruff = "0.6.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
